/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-container": "#dae2fd",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#002113",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "surface": "#f7f9fb",
        "secondary-fixed": "#dae2fd",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "tertiary": "#005338",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "surface-tint": "#4d44e4",
        "primary-container": "#4f46e6",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#c3c0ff",
        "on-secondary-container": "#5c647a",
        "on-primary": "#ffffff",
        "outline": "#777587",
        "tertiary-container": "#006e4b",
        "on-primary-container": "#dbd8ff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#4edea3",
        "primary": "#3525ce",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c7c4d8",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "on-surface-variant": "#464555",
        "on-tertiary-container": "#67f4b7",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3322cd",
        "on-error-container": "#93000a",
        "secondary": "#565e74",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "2xl": "48px",
        "gutter": "24px",
        "xl": "32px",
        "md": "16px",
        "container-max": "1280px",
        "xs": "8px",
        "lg": "24px",
        "base": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
